#!/usr/bin/bash

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width       0 #16
bspc config top_padding	32
bspc config window_gap         0
#bspc config bottom_padding     40

#bspc config focused_border_color	'#1d1f21'
#bspc config normal_border_color		'#1d1f21'
bspc config presel_feedback_color	'#1d1f21'

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config click_to_focus	any
bspc config pointer_modifier	mod4

setxkbmap dvorak
pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D

feh --bg-fill $HOME/.bg.png
polybar -r &
picom -fD5 &

#xautolock -corners 000- -detectsleep -time 5 -locker "i3lock -uc000000"
xsetroot -cursor_name left_ptr &
